### PR TITLE
Fix despawn if Phase Muru adds alive in time phase Entropius die. Maybe need expands SCRIPT_COMMAND_DESPAWN_SELF and use db_script_on_creature_death?

### PR DESCRIPTION
**Pull request by Ulduar**

### CODE REVIEW

**Comment by xfurry** [comment]
I need to investigate this first... I will fix it on SD2 master if required.
Anyway your code has mistakes and it won't work...

**Comment by Ulduar** [comment]
And can explain the reason for not going to work? I looked, and there are similar examples such How it works.

**Comment by Ulduar** [comment]
So far, I'm using here is a hack. It has been tested and works.
``` SQL
UPDATE `creature_linking_template` SET `master_entry`='100000' WHERE `master_entry`='25741' AND `master_entry`='25840'; 

-- Script id: 2574101
DELETE FROM dbscripts_on_creature_movement WHERE id=2574101;
INSERT INTO dbscripts_on_creature_movement VALUES 
(2574101,0,10,100000,0,0,0,0,0,0,0,0,0,0,0,0,'Muru - On Spawn - Summon Muru Controller.'),
(2574101,0,32,1,0,0,0,0,0,0,0,0,0,0,0,0,'Muru - on Spawn - Set Pause Movement = true.');

-- Script id: 25840
DELETE FROM dbscripts_on_creature_death WHERE id=25840;
INSERT INTO dbscripts_on_creature_death VALUES 
(25840,0,35,5,100,0,0,0,0,0,0,0,0,0,0,0,'Entropius - Send AI Event Custom A(inform controller for evade and despawn).');


-- Creature id: 100000
UPDATE creature_template SET AIName='EventAI' WHERE entry=100000;
DELETE FROM creature_ai_scripts WHERE creature_id=100000;
INSERT INTO creature_ai_scripts VALUES 
('10000001','100000','7','0','100','2','0','0','0','0','41','0','0','0','0','0','0','0','0','0','0','0','Muru Controller - Force Despawn on Evade.'),
('10000002','100000','11','0','100','2','0','0','0','0','20','0','0','0','21','0','0','0','0','0','0','0','Muru Controller - On Spawn - False Auto Attack and Combat Movement.'),
('10000003','100000','30','0','100','2','5','25840','0','0','24','0','0','0','0','0','0','0','0','0','0','0','Muru Controller - Receive AI Event Custom A - Enter Evade Mode.');


UPDATE `creature_template` SET `MovementType`= 2 WHERE `Entry`= 25741; 


REPLACE INTO `creature_template` (`Entry`, `Name`, `SubName`, `IconName`, `MinLevel`, `MaxLevel`, `DifficultyEntry1`, `DifficultyEntry2`, `DifficultyEntry3`, `ModelId1`, `ModelId2`, `ModelId3`, `ModelId4`, `FactionAlliance`, `FactionHorde`, `Scale`, `Family`, `CreatureType`, `InhabitType`, `RegenerateStats`, `RacialLeader`, `NpcFlags`, `UnitFlags`, `UnitFlags2`, `DynamicFlags`, `ExtraFlags`, `CreatureTypeFlags`, `SpeedWalk`, `SpeedRun`, `UnitClass`, `Rank`, `Expansion`, `HealthMultiplier`, `PowerMultiplier`, `DamageMultiplier`, `DamageVariance`, `ArmorMultiplier`, `ExperienceMultiplier`, `MinLevelHealth`, `MaxLevelHealth`, `MinLevelMana`, `MaxLevelMana`, `MinMeleeDmg`, `MaxMeleeDmg`, `MinRangedDmg`, `MaxRangedDmg`, `Armor`, `MeleeAttackPower`, `RangedAttackPower`, `MeleeBaseAttackTime`, `RangedBaseAttackTime`, `DamageSchool`, `MinLootGold`, `MaxLootGold`, `LootId`, `PickpocketLootId`, `SkinningLootId`, `KillCredit1`, `KillCredit2`, `QuestItem1`, `QuestItem2`, `QuestItem3`, `QuestItem4`, `QuestItem5`, `QuestItem6`, `MechanicImmuneMask`, `ResistanceHoly`, `ResistanceFire`, `ResistanceNature`, `ResistanceFrost`, `ResistanceShadow`, `ResistanceArcane`, `PetSpellDataId`, `MovementType`, `MovementTemplateId`, `TrainerType`, `TrainerSpell`, `TrainerClass`, `TrainerRace`, `TrainerTemplateId`, `VendorTemplateId`, `EquipmentTemplateId`, `VehicleTemplateId`, `GossipMenuId`, `AIName`, `ScriptName`) values('100000','Muru Controller','','','1','1','0','0','0','11686','0','0','0','114','114','1','0','10','1','3','0','0','33956742','2048','0','0','0','0','0','1','0','-1','0.945','1','7.5','1','1','1','1','1','0','0','2','2','1','1','7','24','0','2000','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','','');

INSERT IGNORE INTO `creature_linking_template`(`entry`,`map`,`master_entry`,`flag`,`search_range`) VALUES ( '25741','580','100000','3','0'); -- if Muru aggro, Muru Controller Aggro.

REPLACE INTO `creature_movement_template`(`entry`,`point`,`position_x`,`position_y`,`position_z`,`waittime`,`script_id`,`textid1`,`textid2`,`textid3`,`textid4`,`textid5`,`emote`,`spell`,`wpguid`,`orientation`,`model1`,`model2`) VALUES 
( '25741','1','1816.25','625.484','69.603','1000','2574101','0','0','0','0','0','0','0','0','5.624','0','0'); 

```

**Comment by xfurry** [comment]
Such workarounds are not acceptable. :wink:

**Comment by Ulduar** [comment]
I know! But purely for myself, I could use it!
Just you know, wait a long time! So I decided to hack to death!

**Pull request closed without merging**
