### PR TITLE
Update SpecialEncounterState For Argaloth, Occutar and Alizabal.

### PR DESCRIPTION
**Pull request by Ulduar**

### CODE REVIEW

**Comment by xfurry** [comment]
In Cata all raid bosses have encounter frames.
I'd suggest to implement a generic way for this directly in the core.

**Comment by Ulduar** [comment]
And that this request hacks? By the way there are NPC Lava Scion - he also has frames.

**Comment by xfurry** [comment]
I didn't say that your solution is a hack.
Bud I know that all raid bosses in Cata, (including old ones) have encounter frames set and removed when encounter starts / ends. Hence, I proposed to have a generic solution.
The exceptions, like the Lava Scion or Ragna transition, can be added in SD2.

**Comment by Ulduar** [comment]
You understand that rely on the instance data in the kernel - it perished idea.
Suppose Encounter IN_PROGRESS - ENCOUNTER_FRAME_ENGADE
Encounter FAIL or DONE - ENCOUNTER_FRAME_DISENGADE. But if you add in the kernel, it will be extended to all the bosses. But there are times when it should not be? The combination of core and SD2 in this case - not good.

**Comment by xfurry** [comment]
The idea was to use this: https://github.com/cmangos/mangos-cata/blob/master/src/game/MapPersistentStateMgr.h#L215

But it might not work as I would have expected...
But anyway, we might need a generic solution for this, since all the raid bosses have encounter frames on aggro, evade and died

**Comment by Ulduar** [comment]
I still do not like this idea.

**Pull request merged**
