### PR TITLE
Add Kologarn Set Corpse Delay(need for visual effect) and delete Freya don't need CAST_TRIGGERED flag for spell 62940. Delete world state Algalon

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by xfurry** [comment]
I'm not so sure that the world state was removed in Cata. I know that I scripted Ulduar using Cata sniff and the world state was still there.
The core might not work with world states in Cata, but that has to be fixed.

For Kolo it's a little tricky.
The standard corpse decay is 1h - https://github.com/cmangos/mangos-cata/blob/master/src/game/World.cpp#L695
But even if set this to 7 days, it would still not help in all cases.
We can set the corpse decay to 7 days and also make the object active so that the grid won't unload. But in case of server restart, the corpse won't be reloaded, so the visual effect is gone...

**Comment by Ulduar** [comment]
``` QUOTE
I'm not so sure that the world state was removed in Cata. I know that I scripted Ulduar using Cata sniff and the world state was still there.
```
You need a an answer from Blizzard? Worldstate even from DBC removed. I can eg Algalon attack on Thursday and go to evade, and on Friday and come Algalon will stand there. So that should be cleaned Worldstate.
``` QUOTE
For Kolo it's a little tricky.
```
The problem remains.

**Comment by Ulduar** [comment]
http://ru.wowhead.com/npc=32871#comments:id=1195108
http://www.youtube.com/watch?v=hoVtBiyagXM
Tell me, do you see there Worldstate? That's right, you do not see, because it is not, I played in Cata and I do not need no videos.

**Comment by xfurry** [comment]
Poke @Ulduar 
Please open new PR only with what is required on https://github.com/cmangos/mangos-cata

**Comment by ghost** [comment]
The sense, it is not working.

**Pull request closed without merging**
