### PR TITLE
Update sound for Anubar Crusher(missing)

### PR DESCRIPTION
**Pull request by Ulduar**
Missing sound for Anubar Crusher(Hadronox Event)

### CODE REVIEW

**Comment by xfurry** [comment]
Thanks. Will push this to SD2 master soonish.

**Comment by Ulduar** [comment]
I wrote this for Cataclysm, and you are talking about the master branch. I do not understand. Wrote, because Cataclysm is rarely updated.

**Comment by Ulduar** [comment]
Why do you closed pull request? In Cata Fork SD2 you are not added.

**Comment by Ulduar** [comment]
Answer complete in IRC! Thanks, i delete branch)

**Pull request closed without merging**
