### PR TITLE
Algalon - don't allow set instance data, if data = done. Also small fixed for two spells.

### PR DESCRIPTION
**Pull request by Ulduar**

### CODE REVIEW

**Comment by Ulduar** [comment]
@Xfurry and @Schmoozerd, you added as a collaborator in the created by me Fork, can edit the, I think.

**Comment by xfurry** [comment]
> @Xfurry and @Schmoozerd, you added as a collaborator in the created by me Fork, can edit the, I think.

We can edit directly in master. :wink:

**Comment by Ulduar** [comment]
``` SQL
The guardian has no reason to enter combat with Thorim, and if it does it's because of stupid Cata core. So please test and work on Wotlk.
```
I do not have a client WOTLK only Cata and Pandaria
Can you update Cata Core? XD

``` SQL
Boss won't get Aggro once it's friendly and evaded.
```
I can refute it. That he did not get aggro after evade, you have to beat him without pets and helpers.
``` SQL
Flag might not be required, but it doesn't hurt. Let's just keep it.
```
Algalon because this flag refuses to cast two spells. I told you that I solved the problem by db_script for RIDE_LIGHTNING spell.

**Comment by xfurry** [comment]
Man.. please understand that I don't want to change the script just because Cata core is totally buggy.
All our scripts behave the same in 3.x, 2.x and 1.x.
The Ulduar scripts have been tested on 335 and they are working fine as far as I can tell.

Things might not work fine in 4.x because of core, not because of scripts. So fixing the scripts is not the solution here.
I can update Cata core and SD2, but I don't have time to work on everything at the same time.

1. Algalon cannot aggro after the encounter is done, because of this: https://github.com/scriptdev2/scriptdev2-cata/blob/master/scripts/northrend/ulduar/ulduar/boss_algalon.cpp#L265
2. CAST_TRIGGERED flag is made especially for casting many spells at the same time https://github.com/cmangos/mangos-wotlk/blob/master/src/game/CreatureAI.h#L55
3. The guardian will not attack Thorim because of Los and because Thorim is passive.

If this is not happening, then the Cata core or YTDB-Cata might have some problems.

**Comment by Ulduar** [comment]
Well, then please just close the pull rekvest. I want to re-create a fork of Cataclysm. I need it to sync. You will also be added as a collaborator.
Immortal Guardian hack solution for Cata - add Thorim Flag NON_ATTACKABLE(Then the guard will not attack him. It has been tested and works. About Algalon - just remove all pets and helpers. It is achievable in principle)
I have plans to create a script to handle the doors in Baradin Hold, create a script to Ragnaros and the Bastion of Twilight. SD2 scripts - no hacks, as I have now.

**Comment by xfurry** [comment]
> I have plans to create a script to handle the doors in Baradin Hold, create a script to Ragnaros and the Bastion of Twilight. SD2 scripts - no hacks, as I have now.

Patch is welcomed :wink:

**Comment by Ulduar** [comment]
``Patch is welcomed :wink:
```
Pull request, I think it will be better!

**Comment by Ulduar** [comment]
Close?

**Pull request closed without merging**
