### PR TITLE
Add open door after death Crimson Hall npc.

### PR DESCRIPTION
**Pull request by Ulduar**
http://ytdb.ru/attachment.php?attachmentid=2722&stc=1&d=1393878412
Need, because after death npc on picture open door to the princes
Please understand, I'm still learning to write scripts - please do not kick!

### CODE REVIEW

**Comment by xfurry** [comment]
What door are we talking about?

These npcs don't need to respawn / despawn based on encounter status.

**Comment by Rushor** [comment]
these are the door which are in front of the council, they should be opened first if the trash in front of it is killed (and they should be closed, while the player fights against the council - that works already).

The question is: how do we save the status of the doors - imagine if there is a servercrash, the door will be closed again on instance join if the trash in front of it is already killed.

**Comment by Schmoozerd** [comment]
In Such a case you add a  new Encounter for the trash-mobs, which you safe and use on reload and when the GO is created.

**Comment by Ulduar** [comment]
In the script, princes also used this door and encounter should not have any state (or fail, or done, or special)

**Comment by Ulduar** [comment]
i suggest:
```CPP
           else if (uiData == NOT_STARTED)
            {
                DoUseDoorOrButton(GO_CRIMSON_HALL_DOOR);
            }
            break;
```
``` CPP
             if (m_sCrimsonHallNpcGuidSet.empty())
             {
                 SetData(TYPE_BLOOD_PRINCE_COUNCIL, NOT_STARTED);
             }
             break;
```

**Comment by xfurry** [comment]
> In Such a case you add a new Encounter for the trash-mobs, which you safe and use on reload and when the GO is created.

Well, there are a few missing answers here:
1. What is the role of GO http://www.wowhead.com/object=201741/empowering-blood-orb which can be found in the middle of the room before the council? I see that it gives a buff, but in the same time it has flag no_interact... @Rushor any ideas here?
2. I'm not sure that saving the encounter is a good idea... These are trash mobs and can respawn in a few hours.

The best idea would be to use a combination of SD2 and ACID, same as I did for the water in SSC: https://github.com/scriptdev2/scriptdev2/commit/1385b30929bc91132c8e43c80f12264fb9fbc969

**Comment by Rushor** [comment]
There is a mage which casts a read beamspell towards the GO (on tc there is an orbstalker inside the go - i hope on mangos too) IF a player runs towards the mage.
IDs i got from sniffs:
ID - 72099 Blood Orb Cast Visual

This beamspell enables the object=201741 and you can click on it. after you clicked on the go, u will get the buff: ID - 70227 AND the GO instantly despawns.

That's what i saw on retail so far :D

**Comment by Ulduar** [comment]
Not only the mage, and he who first Taunt. if the mage, the the mage begins to cast if the knight blood, blood knight, if the adviser, the adviser if the nobleman, the nobleman. When they start to cast a spell, go set flag_nointeract, if you have time to kill him, then go remove flag_nointeract. One player can use the scope and get buff and go setlootstate_deactivated. If the NPC had to finish casting, then buff it gets. buffs different for the player and NPC.
Also do not forget that the channeling spell is only possible if they are close to the sphere, if not around the sphere (3 pack of mobs all these spheres, and 3) they do not have to cast a spell this at all. Simply put, it is necessary to remove EventAI script and write SD2. Or to add new types of Target. Such cases the sea.

**Pull request closed without merging**
